import type { Metadata } from "next";
import { FieldSettingsProvider } from "./components/providers/FieldSettingsProvider";

export const metadata: Metadata = {
  title: "Tetris-2023",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <FieldSettingsProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </FieldSettingsProvider>
  );
}
