"use client";

import type { Metadata } from "next";
import React, {
  Dispatch,
  SetStateAction,
  createContext,
  useState,
} from "react";

export const metadata: Metadata = {
  title: "Tetris-2023",
  description: "Generated by create next app",
};

export type Settings = {
  cellSize: number;
  linesCount: number;
  columnsCount: number;
};

export type setFieldSettings = (prev: Settings) => {
  fieldSettings: Settings;
};

export type SettingsContext = {
  fieldSettings: Settings;
  setFieldSettings: Dispatch<SetStateAction<Settings>>;
};

export const fieldSettingsCreateContext = createContext<SettingsContext>({
  fieldSettings: {
    cellSize: 0,
    linesCount: 0,
    columnsCount: 0,
  },
  setFieldSettings: () => {},
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [fieldSettings, setFieldSettings] = useState<Settings>({
    cellSize: 20,
    linesCount: 20,
    columnsCount: 10,
  });
  return (
    <html lang="en">
      <fieldSettingsCreateContext.Provider
        value={{ fieldSettings, setFieldSettings }}>
        <body>{children}</body>
      </fieldSettingsCreateContext.Provider>
    </html>
  );
}
