import type { Metadata } from "next";
import { FieldSettingsProvider } from "./components/providers/FieldSettingsProvider";

export const metadata: Metadata = {
  title: "Tetris-2023",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: JSX.Element | JSX.Element[];
}) {
  return (
    <html lang="en">
      <body>
        <FieldSettingsProvider>{children}</FieldSettingsProvider>
      </body>
    </html>
  );
}
